# Generated by Django 5.2.15 on 2026-06-10 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('county', models.CharField(default='Nairobi', max_length=100)),
                ('days_ahead', models.IntegerField(default=30)),
                ('interval_hours', models.IntegerField(default=6)),
                ('include_social', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('days_ahead', models.IntegerField()),
                ('scan_type', models.CharField(default='core', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('events_found', models.IntegerField(default=0)),
                ('events_new', models.IntegerField(default=0)),
                ('events_recommended', models.IntegerField(default=0)),
                ('social_posts_found', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('weather_summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('ticket_url', models.URLField(blank=True)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_label', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('is_free', models.BooleanField(default=False)),
                ('location_area', models.CharField(blank=True, max_length=200)),
                ('map_lat', models.FloatField(blank=True, null=True)),
                ('map_lon', models.FloatField(blank=True, null=True)),
                ('weather_forecast', models.TextField(blank=True)),
                ('weather_temp_c', models.FloatField(blank=True, null=True)),
                ('weather_rain_pct', models.IntegerField(blank=True, null=True)),
                ('weather_suitable', models.BooleanField(default=False)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=100)),
                ('ai_reason', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('organizer', models.CharField(blank=True, max_length=300)),
                ('is_recommended', models.BooleanField(default=False)),
                ('poster_image_url', models.URLField(blank=True)),
                ('artists', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=500)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='events_even_date_5e8e1c_idx'), models.Index(fields=['county'], name='events_even_county_035c50_idx'), models.Index(fields=['ai_score'], name='events_even_ai_scor_e4e3f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('alert_type', models.CharField(default='new', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(unique=True)),
                ('platform', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_categories', models.TextField(blank=True)),
                ('preferred_counties', models.TextField(blank=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_events_only', models.BooleanField(default=False)),
                ('outdoor_events_only', models.BooleanField(default=False)),
                ('alert_via_telegram', models.BooleanField(default=True)),
                ('alert_via_ntfy', models.BooleanField(default=True)),
                ('alert_via_whatsapp', models.BooleanField(default=True)),
                ('alert_on_price_change', models.BooleanField(default=True)),
                ('alert_on_weather_risk', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
