# Generated by Django 5.2.15 on 2026-06-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_add_description'),
    ]

    operations = [
    ]
